### ISSUE TITLE
main entry is missing

### ISSUE THREAD

**Issue by lstkz** [krasimir/lsbridge#6]
Here https://github.com/krasimir/lsbridge/blob/master/package.json#L5
There should be a path to the main library.

Below code doesn't work.
```js
import lsbridge from 'lsbridge';
```
Below code works
```js
import lsbridge from 'lsbridge/src/lsbridge';
```

**Comment by krasimir** [comment]
Thanks. It's fixed in the newly released `0.2.0` version.
